### ISSUE TITLE
I only can see the option "Clear NVRam"

### ISSUE THREAD

**Issue by gomgo-github** [sileshn/Ryzentosh#1]
Booting by the USB I see the Clover Boot Loader with only the "Clear NVRam" otion with a Terminal logo, i can't see the instaler logo or anytihng about

**Comment by sileshn** [comment]
Clover?

**Comment by sileshn** [comment]
Change scanpolicy to 0 and try

**Comment by gomgo-github** [comment]
I still having the same problem, y changed scanpolicy to 0

**Comment by gomgo-github** [comment]
i go to put the BaseSystem on the com.apple.recovery.boot folder and try

**Comment by gomgo-github** [comment]
Ok, now i see the USB Name Option but i get stucked on [EDB.AB... ... ... ...]

**Comment by sileshn** [comment]
I can't comment unless i know your system specs, see your efi folder and know what version of OC you are running. Also follow instructions from the link below.

https://dortania.github.io/OpenCore-Install-Guide/prerequisites.html

**Comment by gomgo-github** [comment]
Oh, Ok, i'm using a laptop, the Asus FX505DT with Nvidia GTX 1650 and Ryzen 7

(https://www.amazon.es/ASUS-TUF-Gaming-FX505DT-BQ051-Ordenador/dp/B08DNJMJ77/ref=sr_1_1?__mk_es_ES=ÅMÅŽÕÑ&dchild=1&keywords=&qid=1615131699&sr=8-1&th=1)

**Comment by sileshn** [comment]
U cannot use my files. Your specs are entirely different
