### ISSUE TITLE
My ryzen 5 3600x restart random 

### ISSUE THREAD

**Issue by miguel80799** [sileshn/Ryzentosh#10]
Hello, I have gigabyte x470 aorus ultra gaming with rtx 2060 super disabled and Rx 550 Lexa working fine, but when I have been using it for a while without cause it restarts.  can you help?  

*use the translator I speak Spanish*

**Comment by sileshn** [comment]
I am busy with other projects now. Will ping u when I am free. In the meantime, send me your efi

**Comment by miguel80799** [comment]
thank you! 
EFI DRIVE LINK: https://drive.google.com/file/d/16O-7vMg0tfBog5accRPFqEE6ptC3YOGO/view?usp=sharing
