### ISSUE TITLE
Ryzen 5 1600 AF and RX6600 Black Screen Problem after Verbose

### ISSUE THREAD

**Issue by Ent1rebyte** [sileshn/Ryzentosh#11]
Hello,

Two years ago, I had a successful hackintosh installation (Mojave) and recently I upgraded my GPU to RX6600 and wanted to install Monterey. However I'm not able to load after verbose while booting. I tried many EFIs. Most of the time i got stuck on the verbose boot log screen with those EFI files.  Your EFI fixed stucking on verbose but this time I am getting black screen after verbose and there is no signal on my display. My mainboard is exactly the same as yours. All system components except gpu are same as I used in Mojave. I'm also sharing my full specs below. Any suggestions ? Thanks in advance!

MotherBoard | Gigabyte B450 Aorus Elite
CPU | AMD Ryzen 5 1600 AF
GPU | AMD Radeon RX6600 8GB
RAM | G Skill 32 GB (8x4)

**Comment by sileshn** [comment]
My GPU is different from yours. You need to make changes for it to work. Plz go thru the dortania guide
