### ISSUE TITLE
I have a question

### ISSUE THREAD

**Issue by garisbaldy** [sileshn/Ryzentosh#12]
I currently have the following equipment, aorus pro WiFi b450 motherboard, Ryzen 3600 XT, 16 GB ram, Rx 570 aorus GPU, my question is if the EFi you prepared works for me on mine.

**Comment by sileshn** [comment]
Wifi won't work. I have a seperate wifi/bt combo. Rest should work

**Comment by garisbaldy** [comment]
Last night I tried to boot Monterrey but when it started it stopped, can you upload the EFI folder of your configuration?

**Comment by sileshn** [comment]
Y upload? Just download the repo.

**Comment by garisbaldy** [comment]
ok i will try it thanks a lot for the help bro 💪

**Comment by sileshn** [comment]
Also remove the wifi/bt kexts and their entries from the config file since you don't have the required hardware for those kexts. Also serial/parallel port, 4g decoding and secure boot should be disabled in bios.

**Comment by garisbaldy** [comment]
ok, thank you very much Bro God bless you always 🙏

**Comment by garisbaldy** [comment]
Thanks for the help, it is already being installed, but I don't understand why it takes so long, 11 hours and 57 minutes, even though it is being installed on an SSD, do you know how long it took you?
![Uploading PXL_20220901_020018989.jpg…]()

**Comment by sileshn** [comment]
30 to 40 minutes, 4 reboots in total

**Comment by garisbaldy** [comment]
but that's when it's a full image not when you're reinstalling the Mac version, because the rest DMG was run through Python and was only 650MB

**Comment by sileshn** [comment]
I don't understand what u are saying.

**Comment by garisbaldy** [comment]
Now if I go to the installation part, thank you very much Bro
