### ISSUE TITLE
Everything is working Except the Ethernet

### ISSUE THREAD

**Issue by gmraselparvez** [sileshn/Ryzentosh#15]
Everything is working fine for me except the ethernet. It shows my ethernet is connected but I can't use the internet. Can you tell me how to solve this?
![image](https://user-images.githubusercontent.com/58115792/194047771-c039cf96-ff6b-4cbb-80ad-575e237f3029.png)

**Comment by sileshn** [comment]
Depends on what Ethernet card you use. My setup works only for rtl8111. If yours is different, then you need to go thru the ooencore guide and find a suitable next.

**Comment by gmraselparvez** [comment]
I am using B450 Mortar Max and my ethernet model is same to yours

**Comment by gmraselparvez** [comment]
Realtek® RTL8111H-CG

**Comment by sileshn** [comment]
Try older versions of the kext from the link below

https://github.com/Mieze/RTL8111_driver_for_OS_X

**Comment by gmraselparvez** [comment]
still not working

**Comment by sileshn** [comment]
Can't help then
