### ISSUE TITLE
My PC glitches out with this efi, the monitor glitches and my pc reboots, pls help me

### ISSUE THREAD

**Issue by fraktosh** [sileshn/Ryzentosh#16]
Specs: 
CPU: AMD Ryzen 7 2700X 
GPU: AMD Radeon RX 590, AMD Radeon RX 560
RAM: 32 Gb Gskill
MOTHERBOARD: Gigabyte B450 Aorus Pro

**Comment by sileshn** [comment]
It's incompatible. U have a 16 core processor. I have a 12 core processor.

**Comment by GeorgeV220** [comment]
Hello,
you can try my own config.plist but I don't think it will work for you. Give it a try tho
https://github.com/GeorgeV220/Ryzentosh

**Comment by GeorgeV220** [comment]
> > Hello,
> > you can try my own OC but I don't think it will work for you. Give it a try tho
> > https://github.com/GeorgeV220/Ryzentosh
> 
> does it work with Ventura??

it should work with Ventura

**Comment by sileshn** [comment]
You can try reverting the changes from the commit below as my earlier CPU was Ryzen 2700. 

https://github.com/sileshn/Ryzentosh/commit/aefb63dc1196f582a894e137cd7578c0e1d03ee5

Then remove all entries that are not applicable for you from the deviceproperties in the config file . Also remove the kexts not needed for your setup. It may work than.

**Comment by fraktosh** [comment]
> > > Hello,
> > > you can try my own OC but I don't think it will work for you. Give it a try tho
> > > https://github.com/GeorgeV220/Ryzentosh
> > 
> > 
> > does it work with Ventura??
> 
> it should work with Ventura

thank you very very much, its working I think it was a problem with my patches, I replaced everything. Thanks for helping me out

**Comment by fraktosh** [comment]
> > > > > Hello,
> > > > > you can try my own OC but I don't think it will work for you. Give it a try tho
> > > > > https://github.com/GeorgeV220/Ryzentosh
> > > > 
> > > > 
> > > > does it work with Ventura??
> > > 
> > > 
> > > it should work with Ventura
> > 
> > 
> > thank you very very much, its working I think it was a problem with my patches, I replaced everything. Thanks for helping me out
> 
> I hope you have changed the serial numbers and etc

I just used my old efi, so its fine thanks again for helping
