### ISSUE TITLE
What is the method used to boot Manjaro Linux?

### ISSUE THREAD

**Issue by fhilipecrash** [sileshn/Ryzentosh#17]
Hi, I would like to know how you did to boot Manjaro Linux, I currently use OpenLinuxBoot but I find it limited because I haven't found out how to pass parameters to the kernel at boot time. Do you chainload with GRUB and the like or do you use an entry for EFISTUB? I couldn't identify the method looking at your config.plist

**Comment by sileshn** [comment]
None of this is required for me. I install manjaro in a separate disk with its own efi partition. OC picks it up automatically. For the icon, I add the manjaro.icns from my theme to the manjaro efi folder renamed as .VolumeIcon.icns

**Comment by fhilipecrash** [comment]
Exactly, from what I could see OpenLinuxBoot uses some GRUB binaries and configurations to work, so I simply generated the grub.cfg file based on the /etc/default/grub file parameters. That's why I closed the issue because thinking a little I managed to solve my problem
