### ISSUE TITLE
GPU runs at full speed regardless of load

### ISSUE THREAD

**Issue by lovelock** [sileshn/Ryzentosh#19]
I've been using your EFI( with my own SMBios) for years and thank you for that.

But recently I realized that the GPU is always running at full speed as soon as the power button is pressed. I have two ryzentosh machines, one with RX 580 and the other with RX 560D, both of them have the same problem.

Actually I sort of don't care about the fan speed, what bothers me is the noise of the fans.

I wonder if there's something I can do to turn on dynamic speed

<img width="698" alt="image" src="https://user-images.githubusercontent.com/2208731/209905413-1a97ff22-8f71-4a58-80b1-06c4434fd3b8.png">

Thank you.

**Comment by sileshn** [comment]
I know that Vega cards have a software to control fan speeds, but I am not sure of one that exits for the cards you have. Your best bet to find a solution is to post your query at the amdosx discord server.

**Comment by lovelock** [comment]
Thanks for your suggestion. Perhaps I've found the cause, I installed a Windows 10 and AMD graphics drivers, the fan was running at full speed but the driver shows 0. I flashed vbios of the card but nothing changed. Maybe the graphics card is broken, I'll break it up and check it out
