### ISSUE TITLE
Thank you bro, your config is perfect for me

### ISSUE THREAD

**Issue by lovelock** [sileshn/Ryzentosh#2]
With your config, I upgraded my 10.15.7 to 11.5.1 and all works good. Besides it now can sleep. I am all tears. Thank you bro.

My specs are motherboard MSI B450 Motar Max, CPU AMD 3600, GPU AMD RX580 8G 2304SP, SSD SN550 1T

**Comment by sileshn** [comment]
No problem. Glad to be of help.
