### ISSUE TITLE
AMD RX 570 HDMI Audio is cracking

### ISSUE THREAD

**Issue by deibysartigas** [sileshn/Ryzentosh#20]
Everything seems to be working but I can't hear anything good using HDMI audio. Pops and Cracks everywhere. Audio is good with my internal audio and USB audio card, btw.

My rig:

Asrock B450 Fatal1ity Gaming AC ITX
AMD Ryzen 5 3600
Corsair Vengeance 16 GB (8+8) 3200 MHz
MSI Radeon RX 570 Armor 4G OC 4GB
NVMe Western Digital SN750 500 Gb

What do you think could be?

**Comment by sileshn** [comment]
https://github.com/AMD-OSX/AMD_Vanilla#information-on-the-fix-pat-patch

**Comment by deibysartigas** [comment]
> https://github.com/AMD-OSX/AMD_Vanilla#information-on-the-fix-pat-patch
> 
> Shanee' patch is enabled in my config. You can try switching to algrey's patch to see if it fixes your issue

It's done, buddy. Thank you very much. You're the best!.
