### ISSUE TITLE
stuck on pci error can you help me

### ISSUE THREAD

**Issue by UsetUset2244** [sileshn/Ryzentosh#23]
pci build flags appears my system specs are 5600h with 6800m graphics card lenovo laptop
![4](https://user-images.githubusercontent.com/110706082/235374159-d6553ae6-0711-4186-8a55-faa0a26a3665.jpg)

**Comment by sileshn** [comment]
Laptops are not supported. Please read the dortania guide before you try out anything.

**Comment by UsetUset2244** [comment]
no its supported ive red it because my vega 7 in the supported page why do you insist on closing the issue ba bye im just gonna leave hope someone find this and help me @sileshn

**Comment by sileshn** [comment]
Dude. How can you use this EFI for your setup? I run a desktop with Ryzen 3600 and RX 570. Are your specs the same? How will this EFI work for you? Use some common sense. I am closing it because it is of no use to anyone.

**Comment by UsetUset2244** [comment]
ill search hope i find it if it supported than i should be able to find it in the future ba bye thanks for your time
