### ISSUE TITLE
SIP disable -> slow laggy OS

### ISSUE THREAD

**Issue by 83427** [sileshn/Ryzentosh#25]
Hello, i need to disable SIP cos I need to use unsigned kext "Kx audio driver" for my newly bought creative audigy Rx sound card. Problem is that if I disable SIP, macOS is very slow and laggy. I can't copy or delete files, I can't mount dmg, I can't open any settings and I can't run 80% of apps. Sometimes is impossible even restart or turn off the computer. Once I enable SIP, everything is smooth, fast and perfect. I need to know if its specific problem of my computer (for example BIOS settings) or if its problem specific to this EFI. Thanks for your help.

**Comment by sileshn** [comment]
I don't know. I have never disabled SIP on my system. You'll have to look for support elsewhere.
