### ISSUE TITLE
is opencorre0.9.3?

### ISSUE THREAD

**Issue by aicynide** [sileshn/Ryzentosh#26]

**Comment by sileshn** [comment]
https://github.com/sileshn/Ryzentosh/commit/9ce0b55e5cbcc496f3ee042a49fd887623d40450

**Comment by aicynide** [comment]
Thanks man. I hope this works for my Gigabyte B450 Aorus Elite mobo and Ryzen 5 processor

**Comment by aicynide** [comment]
Enable github "Discussion" please
