### ISSUE TITLE
stuck on AAPL: #[EB|LOG:EXITBS:START]. Opencore 0.9.3

### ISSUE THREAD

**Issue by citruspuma** [sileshn/Ryzentosh#31]
hello (i'm new here - still getting my bearings). 

I've followed the dortania guide to a T (thanks be to those folks), but keep sticking.  After brief a brief loading sequence, I get stuck at 'couldn't get array serialized at 0 index.' then, I'm able to select the USB, which reveals the apple logo (but no load bar). This stalls infinitely. the last line of the log reads 'AAPL: #[EB|LOG:EXITBS:START]'. (log attached).

I've also tried all prospective solutions at [dortania](https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/extended/kernel-issues.html#stuck-on-eb-log-exitbs-start), to no avail. Can I get any pointers to proceed? 

System: 
CPU: Intel 13600k 
GPU: Asrock Radeon 6800xt 
MOBO: Asrock Z790M

Thanks in advance. I know there's some real big brains here. 
[opencore-2023-07-30-213322.txt](https://github.com/sileshn/Ryzentosh/files/12210125/opencore-2023-07-30-213322.txt)

**Comment by citruspuma** [comment]
i now realize this is likely not an appropriate place to post. like i said - still getting my bearings. I also tried to upload EFI, but it's too big. my apologies for my evident ignorance.

**Comment by sileshn** [comment]
https://discord.gg/Wxam8aH
