### ISSUE TITLE
problem with macOS Catalina 10.15.7 bootloader

### ISSUE THREAD

**Issue by valkruss** [sileshn/Ryzentosh#32]
https://ibb.co/GknNTXC
There is no installer in the OpenCore loader .dmg Catalina

**Comment by sileshn** [comment]
What? I don't understand

**Comment by valkruss** [comment]
there is no Catalina installer in openocre

**Comment by sileshn** [comment]
I still don't understand. Why are you posting it here? Are you looking to create a Catalina install USB?

**Comment by valkruss** [comment]
yes

**Comment by sileshn** [comment]
https://github.com/corpnewt/gibMacOS

You'll have to install python

**Comment by valkruss** [comment]
hello

**Comment by sileshn** [comment]
Common dude. I gave you the link to gibMacOS.  Toggle to recovery only mode and download the latest recovery image. Rest you need to figure out from the readme file of the project.

I am closing the issue as it has nothing to do with this project.
