### ISSUE TITLE
SSDT-SLEEP-PTXH.aml

### ISSUE THREAD

**Issue by marekk1717** [sileshn/Ryzentosh#33]
What is the purpose of SSDT-SLEEP-PTXH.aml
It seems that I have some strange issues with USB on Ventura 13.5.1. My network keeps disconnecting on builtin eth and USB adapter. Wifi works fine.

**Comment by sileshn** [comment]
https://dortania.github.io/Getting-Started-With-ACPI/ssdt-methods/ssdt-easy.html#so-what-can-t-ssdttime-do
