### ISSUE TITLE
Everything worked aside Keyboard

### ISSUE THREAD

**Issue by joeadeoye5** [sileshn/Ryzentosh#34]
Hello,

I downloaded this EFI to boot MacOS Sonoma 14.1 in VMWare on my PC. Everything works as expected, but keyboard didn't work

PC Specs
======
CPU: AMD Ryzen 9 5900 12 Cores
GPU: AMD Radeon RX 580 8GB
64GB DDR4 Ram
Gigabyte B550M Motherboard
HID Wireless Keyboard and Mouse (it has USB receiver plugged into USB port)
Host OS: Microsoft Windows 11

VMWare Workstation Pro 17
OS: Microsoft Windows
OS Type: Windows 11 x64

Steps to reproduce
===============
1. Create VM with guest OS: Microsoft Windows and OS Type: Windows 11 x64, with 8GB Ram, 80GB HDD and 6 Cores CPU
2. Attach MacOS Sonoma 14.1 USB Stick to the VM (with the EFI of this repository in the EFI partition)
3. Boot from the USB
4. After the installer gets to the recovery page (the page to select disk utility), Mouse is working, but Keyboard isn't

What i have tried
=============
1. Set XhciPortLimit to false
2. Mapped USB with USBToolBox and place in kexts folder and snapshot config.plist
3. Included OpenUsbKbDxe.efi in drivers folder
4. Included Ps2KeyboardDxe.efi in drivers folder
5. Used UsbInjectall.kext
6. Added SSDT-CPUR.aml to ACPI folder

My keyboard and mouse is a 2.4G Wireless, it uses one single USB receiver for both keyboard and mouse. The mouse worked, but keyboard doesn't. I even tried to complete the installation with only mouse (leaving any textfield with default text) and the installation completed successfully without error. The only problem is keyboard. 

Please help!

**Comment by sileshn** [comment]
I have no experience of running macos on VMware. From what I see, it looks like an issue on the VMware side.
