### ISSUE TITLE
This EFI also works for Asus TUF B450m Pro Gaming

### ISSUE THREAD

**Issue by lovelock** [sileshn/Ryzentosh#4]
Graphics Card is weird, but it works like a charm
<img width="698" alt="image" src="https://user-images.githubusercontent.com/2208731/137055775-d735d74f-b143-4b7c-9a04-7fc582b9ca96.png">

**Comment by lovelock** [comment]
@sileshn Thanks, I'll check it out.

**Comment by vitorcamposss** [comment]
link please
