### ISSUE TITLE
Nice job ,very useful

### ISSUE THREAD

**Issue by zzduci** [sileshn/Ryzentosh#40]
Your EFI file works very well and can be upgraded online via OTA, you use the Kodi program? It can be installed normally, but when you exit the software, the system freezes very frequently.

**Comment by sileshn** [comment]
No. I don't use kodi on my hackintosh. You can join the [amdosx discord](https://discord.gg/EfCYAJW) server or the [amdosx forum](http://forum.amd-osx.com/) to ask for help.
