### ISSUE TITLE
Don't boot on update or USB installation - Big Sur to Monterey

### ISSUE THREAD

**Issue by paulomcnally** [sileshn/Ryzentosh#5]
Hi @sileshn 

Any idea?

The EFI work for Big Sur, on Monterey crash on boot.

Components:
https://valid.x86.fr/238hc7

![IMG_20211212_233142233](https://user-images.githubusercontent.com/181533/145759352-4de4b5ab-a592-46be-8df9-d80b0ed38b2d.jpg)

**Comment by sileshn** [comment]
Need your system info

**Comment by paulomcnally** [comment]
What Is systeminfo?

Have a example Of system info?

**Comment by sileshn** [comment]
Send me your EFI

**Comment by paulomcnally** [comment]
My EFI Is a copy Of this repository.

**Comment by sileshn** [comment]
Then it will not work. Your GPU is different. Check opencore guide for boot-args needed for your GPU. I am not in front of a system so cannot remember the ones required. 

Or

I'll take a look when I get back home tonight

**Comment by paulomcnally** [comment]
On this repo i have the dortania steps for monterey with boot-args for my GPU

https://github.com/paulomcnally/opencore-monterey

on this repo i have my actual Big Sur with legacy Open core.

https://github.com/paulomcnally/opencore-bigsur

I change boot-arg for my GPU on this repo but dont work.

**Comment by laranz** [comment]
@paulomcnally Check this troubleshoot guide: https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/extended/kernel-issues.html#stuck-on-eb-log-exitbs-start

**Comment by sileshn** [comment]
Your EFI is not proper. Running ocvalidate returns a lot of errors. Attached error log. 

`
OCS: Missing key Flavour, context <Tools>!
OCS: Missing key Flavour, context <Tools>!
OCS: Missing key Flavour, context <Tools>!
OCS: Missing key Flavour, context <Tools>!
OCS: Missing key Flavour, context <Tools>!
OCS: Missing key Flavour, context <Tools>!
OCS: Missing key Flavour, context <Tools>!
OCS: Missing key Flavour, context <Tools>!
OCS: Missing key Flavour, context <Tools>!
OCS: Missing key Flavour, context <Tools>!
OCS: Missing key Flavour, context <Tools>!
OCS: Missing key Flavour, context <Tools>!
OCS: Missing key Flavour, context <Tools>!
OCS: Couldn't get array serialized at 0 index!
OCS: Couldn't get array serialized at 1 index!
Serialisation returns 15 errors!

Booter->Quirks->ProvideCustomSlide is enabled, but OpenRuntime.efi is not loaded at UEFI->Drivers!
CheckBooter returns 1 error!

UEFI->Quirks->RequestBootVarRouting is enabled, but OpenRuntime.efi is not loaded at UEFI->Drivers!
CheckUefi returns 1 error!
`

**Comment by paulomcnally** [comment]
@sileshn I'm going to check. Thank you.

Thanks @laranz

**Comment by paulomcnally** [comment]
@sileshn 

What do you think of this adaptation?

https://github.com/paulomcnally/opencore-monterey-amd/commit/8ac9594f90ecbc5b1d5141a475d9fe339f2daee9

I have 8 cores on my CPU.

![Screen Shot 2021-12-15 at 20 13 40](https://user-images.githubusercontent.com/181533/146295397-c3fa8123-33d3-4e05-8b19-a582c677f6b2.png)

**Comment by paulomcnally** [comment]
![IMG_20211215_202327840_HDR](https://user-images.githubusercontent.com/181533/146296438-9240c884-2e54-4787-822f-8e13ddb05fcc.jpg)

After select opencore on boot options 😰

**Comment by sileshn** [comment]
Give me some time. I'll send you an EFI. What's your wifi/network card? I also need your pci list from [hackintool](https://github.com/headkaze/Hackintool)

**Comment by paulomcnally** [comment]
@sileshn 

This is my wifi card.

https://www.amazon.com/-/es/fenvi-T919-BCM94360CD-Beamforming-PCI/dp/B07VCCZS54

This is PCI list? -> https://github.com/paulomcnally/pcie ?

![Screen Shot 2021-12-15 at 20 41 19](https://user-images.githubusercontent.com/181533/146298192-9ca31ea6-b315-499f-b81a-6571932c0df5.png)

**Comment by sileshn** [comment]
Yes. Save it and send me the .plist file

**Comment by paulomcnally** [comment]
I have secureboot disabled on my bios.

This is the .plist file exported https://github.com/paulomcnally/pcie/blob/master/pcidevices.plist

**Comment by sileshn** [comment]
OK. I'll make a efi for you and send it sometime today. Also make sure of the bios requirements I mentioned in my previous post.

**Comment by paulomcnally** [comment]
Above 4G Decoding Disabled

![IMG_20211215_205013353_HDR](https://user-images.githubusercontent.com/181533/146299258-1e643548-2948-4865-90b0-17ed4c702dc1.jpg)

**Comment by paulomcnally** [comment]
Secure Boot Disabled

![IMG_20211215_205453394_HDR](https://user-images.githubusercontent.com/181533/146299637-a2cce573-82c2-41cf-980e-0afcb073266d.jpg)

**Comment by paulomcnally** [comment]
I don't see serial ports on My BIOS 😔

**Comment by sileshn** [comment]
Try this EFI and see if it works. Do not make any changes if you want to report issues.

[EFI.zip](https://github.com/sileshn/Ryzentosh/files/7724647/EFI.zip)

**Comment by paulomcnally** [comment]
How can I reward you for your time?

Thanks!!!

![IMG_20211215_232130709](https://user-images.githubusercontent.com/181533/146312960-eae105ff-ef85-429a-850b-1d3f5160bd37.jpg)

**Comment by sileshn** [comment]
Its fine. Have fun with monterey

**Comment by paulomcnally** [comment]
Thank you. https://github.com/paulomcnally/opencore-monterey
