### ISSUE TITLE
Core count

### ISSUE THREAD

**Issue by Higher08** [sileshn/Ryzentosh#6]
Hello, where do I need to change the core count? Here https://github.com/sileshn/Ryzentosh/blob/ffc88ec811cbf73049ef4ff29d418914b4fe8807/EFI/OC/config.plist#L555?

**Comment by sileshn** [comment]
Procedure is mentioned in the readme

**Comment by Higher08** [comment]
I don't understand this _the Replace value only_.
Is it this value?https://github.com/sileshn/Ryzentosh/blob/9cceb89f023b4b60ee5d5f6f1593b97003bd576a/EFI/OC/config.plist#L571

**Comment by sileshn** [comment]
https://github.com/mikigal/ryzen-hackintosh#modifying-kernel-patches
