### ISSUE TITLE
Ryzen 7 5700G

### ISSUE THREAD

**Issue by GeorgeV220** [sileshn/Ryzentosh#9]
Hello,
I'm new to the hackintosh and I can't understand it in one extend (I only have managed to install macOS in i3-9100F with an RX 550)
I tried to boot macOS but in the opencore gui I don't have available the macOS recovery available in order to boot in it, the only option is to boot to windows.

I'm using Ryzen 7 5700G, RX 6600, MSI B450-A PRO MAX and 16GB DDR4 Ram from corsair.

**Comment by sileshn** [comment]
Are you using this efi for your setup? If yes, it won't work. Your system specs are entirely different from mine.
